import {
  IMAGE_TEMPLATE,
  PRODUCT_OPTION_TEMPLATE,
  PRODUCT_OPTION_VALUE_TEMPLATE,
  PRODUCT_TEMPLATE,
  PRODUCT_VARIANT_TEMPLATE,
  VIDEO_TEMPLATE
} from './fragments/fragmentTemplates';


export default {
  IMAGE_TEMPLATE,
  VIDEO_TEMPLATE,
  PRODUCT_OPTION_VALUE_TEMPLATE,
  PRODUCT_OPTION_TEMPLATE,
  PRODUCT_VARIANT_TEMPLATE,
  PRODUCT_TEMPLATE
};